MIHOMO_WEB_UI_PASSWD: ENC[AES256_GCM,data:obTIEvqvGmmV4XnW0A==,iv:xfthW/2bczoea8IJA1LIqxoh1YIT81xIPNRQZTBTJKE=,tag:4vms1ulzw3n4yOPZ24QFkw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQdkdMNXpRSlFNUGI5SHB0
            dGJMVkdiK0hVbUw2RVRtbks4czRlUUZRT1RzCkhZZnBlSWFFcUJyTlN1OFVMeVJO
            Vi9mMFBPaUlwWkFvaU9ZdllXKzFlL3cKLS0tIGpqQWlpVGhJVjZmeDlXTUFCRlZz
            U2JoZXN0elZXSUFGV0RhWFFhaTNxSWcKbrgbJRi9j7d5cIm+LDl/DTYc3h+xECSg
            aCGBNLHnqIWZI4SwzZo/zgxhFYooeFh2N5xUaOATo7dC+xCX47L+yA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10e9kadcyeqfruje92gxzax3mntxfzzqm6f64frz6hr0ns6c2d3rqu36l7c
    lastmodified: "2026-05-29T15:31:08Z"
    mac: ENC[AES256_GCM,data:xwujTz63Kra21RRfbSOTxewymwbx6cEtXtEpaBg77x5ggaifiPKB9QNsJuZ2G5Acduw6OqqnBcYI6AzAk6ifLI2ChkQEV+/vzFCiN+M5UVA1+hjF8uyJL42C5CxNpW2YPtNsFMzPHdE7w4+YPmi7qdXIMvWgHBrKrjDCuE/sY1k=,iv:LHcmlNy7KdGNCV1hVZLUJPiUKEbKIAjC66gkPA3bA+k=,tag:2fBLUDz+aM9h7FTfJxWuvg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.0
