hello: ENC[AES256_GCM,data:gxsAjAjBK32cH+65k65lzGxdCZuqGTWgW8KTIRAVEOodU1MoYlI1ubAtE/Av,iv:alisjQNsVFpqV2x+8jEHuhPtJO7HSRaJwMkcB54DH6s=,tag:b34GrLthuEHFVJYwJKhmQg==,type:str]
example_key: ENC[AES256_GCM,data:w6HKDHfBuh9xV1r6qg==,iv:YJ5IDcPclkzMpFElRZr9xhCO9M6YsX4rBCv6ga7CwPw=,tag:u5QdShkQIB1v2KuNDbAIMA==,type:str]
#ENC[AES256_GCM,data:ZG/Y1X/qKGamYb1Ei9gK6Q==,iv:y5dh1QmU3RAfWrmArhhw2zxHZ6Smnq1ADfv8GlJM/3w=,tag:LtshHMzctyNIaWjmTRd1NA==,type:comment]
example_array:
    - ENC[AES256_GCM,data:77nhbqtrdtmutXGF2M4=,iv:ksjrGWaU0/iK8q1Eb75O0IqF74fOHcE3M0iGyzc90Sw=,tag:EuoAKK+t2RJuXBtGvVedbQ==,type:str]
    - ENC[AES256_GCM,data:eygOZcrWz7N2cOLvLhk=,iv:3wnl9Y2SKVm21D8YoC6zDrw8+bpNdmingaEurOK9xEQ=,tag:YQgzCwejUjdxgp2MOkMGRw==,type:str]
example_number: ENC[AES256_GCM,data:Nuou63fYRkMnEw==,iv:pDVj56e2cu5Lpm6/jyC9E11SjEzyNut3f0uJMYJjS20=,tag:UEtyAVxHlBcJMn/hifNWeg==,type:float]
example_booleans:
    - ENC[AES256_GCM,data:mPNV/Q==,iv:QtmqDV8yYl71HvnouMZ/cSrjg4e3rW1YPZ3e5SoA7N4=,tag:Ruw4tZkq8vDyAbSKo6Mzcw==,type:bool]
    - ENC[AES256_GCM,data:USgDCys=,iv:xXi8werRtG3+BkPiVY3Tz2h4uQecMbYMf8uDPR1ZRXI=,tag:LjXQdj1DsBd8qMz0iiX9AQ==,type:bool]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2Y21qKzBwMEg5dnlkN0RC
            b2l3RXRZOWVtTkg4emFwT3M0MFY4N0J2RW53Cm1lOFpiRlZJdjlrODJ2akFKSEVr
            Q0lwbVBzRW1kZmM0eTBIeWlNdjJ3YUUKLS0tIGxUVUFSbWk1ZWh4SHlQQWlUMUYz
            NnFCSU5UN2JualFzN0RadktnL1ZLYjAKUvvvOqn4ekNC9u67hq4LW/MxpSE6QxvS
            ygZwsG7CKsfc1Eysg5UrYl5Lf4Y1+kgyepEtJb1RPp6m/tQyGER2Aw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xdlmmj7gvvmvpl7n28yv6l9zsrrlazyunesyrzhzy37n59zexepsp4gpxn
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqOHN2NnlabVVGK2lNMkc1
            eWdwdERZakZMWWNTNThMbDMxVlo2aVRTL2lRClRKQTRaaTVUQmdsdVZsZ2pONnZx
            RHE0ZktqeHloNzVxVlpBUEtaK1pVUzAKLS0tIG40ZlhYMHdOUTNiWWFHcFk0QjZX
            RWxCeExvVG5wWmg5WU9CeSsxa3lUYWcKXLLQaU3AEkcpHz1zrtWJb68yoWTNQJsv
            6iCXSqUWLo44MejrI+t2ZWo9pTfZEv9eioBRV46w5T88wx9xMO+LNg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10e9kadcyeqfruje92gxzax3mntxfzzqm6f64frz6hr0ns6c2d3rqu36l7c
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxTlpPRHFianRBNEt2OXI5
            OE82MFhrRitNZlRvUFlzeHFOazIxdUwxRlhrCi9zbGVmVTZnZjBHZXovV0hERjI1
            b2pwOTEyK0ZmaGYvRDZveE9qOG4rOWcKLS0tIDlERmtVNUNQWVgxclNEZjNnT1M1
            bWdyb3JLZHJoUVh2NHl5QjBacXV2dFkKmwjEHz2bPMdJJrtgTRuFhXizx4nEnzyr
            LmHq+OIeUQx1BV/T6C08xd1rvHbyi/7L3tv5fGZG5SXx0q74YnYSog==
            -----END AGE ENCRYPTED FILE-----
          recipient: age18gjva8lxepd4gc5whz73q39xjerphtm6nmfaax9ye9f2dzsj293qgg7xw5
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYNU1JVFBrTjJvcTR4Qmwx
            aFJYRjZybmxjRGFucU1sSUFEdzgweUQxem5FCmp2WEh4a25FSTd4TkFQeXB4Q1VS
            RWRCMW1WZkpabzlrdWFBYXBoQ1lxb2sKLS0tIDQ1SC9xcTUxWWluL3lFcURJdDRh
            Wnc0ODJUMTZ3SXhVVVpGQzF5blRJYlkKLHli53pZs2Bszq9yR1+x9cxB6VV8SIBh
            rtSqfccTdqKLlvh5Op83YH15tMps9DFlb4HLbIH5+fqsYaISv4MM7Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age18cwlfuth4jpz03u9wzwq5rxxxx50w9e0me9sjqt29dtra0xh33ss7xtfs5
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiM0h1Ym1qRGYwWDM2Qkw4
            UmRsWUREcC9jNlFLUVlRT01ycityNERqdWgwCmFUSTNhZ3V3YTAwbkgwZ0psM3dG
            eEVzb0kxZVJ1MGppNHJrc0UwamJ6U2sKLS0tIE5MZmFDMTJtSVFkZisyM3RGOG5p
            VVZ3eGtSdU5NcEUxbHVIVE9NOC9NUnMKoMJQjoft46RRrBF5f04DBCCYMNazmlZy
            rehsttFeEruVn/FXcBBV3IHQ0UJGS98Ykp96WUaEHvvSyimMh5A+Mg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1se6rw68dnwf6896j8r2v2vjf3kvm5l2x2220epdnm4k2xwzjee7qqj9hl8
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3YXhHMWVWMk5rR1BtMjlh
            L0prQy9FU2xZd0pBeGpYUno0U09iUVBON1VjCkFRM2ZkK1NVcTZpb2ZDcVVhNUd0
            bndEdmtRcnJtWFR6ZUQ3RVpqQkdET2sKLS0tIEo4VDF0bUNPY1hDR1pmQzNmNXVR
            KzZvenF5QTZ1eU04MmtQUFpNck9kWHMKClZbty+i4FVie4JJZrHNv7Df4dnUqEX4
            XG8I/4naHJO/kUypj9HcMCzitlod+G+MmCpk/OZIQnWMUVOgCVDMkw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ylwmymkx7vzjw9mx2kuwnjzlkrf7wj54gkj0rg3f9c43lqsd5gustdjxam
    lastmodified: "2025-09-12T23:20:40Z"
    mac: ENC[AES256_GCM,data:E7E+hQnN5eeKOs4faElgkeMukSbyJTwDYcf3+xDLh2WC9adq6oCaj7I5siydEZ0JzIZvdMN3ygxTUqt3Cg4vYDN5XHuxHWagcEjZ9+U+W6JhutUmPcSxGWVGjtPDTWCD+xJazNuT40yvLEOK2XxA+zwPIaN/2pjARbrFa0k+Olk=,iv:CdhbcJsdPGF8UH3qOTEnkXl8l8mkl6yMqyIoYrVYoUc=,tag:WwtyCzstqBUGJaeYuc3+MA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
